/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './admin.html', './src/**/*.js'],
  theme: {
    extend: {
      colors: {
        surface: 'rgb(var(--c-surface) / <alpha-value>)',
        'surface-lowest': 'rgb(var(--c-surface-lowest) / <alpha-value>)',
        'surface-low': 'rgb(var(--c-surface-low) / <alpha-value>)',
        'surface-cont': 'rgb(var(--c-surface-cont) / <alpha-value>)',
        'surface-high': 'rgb(var(--c-surface-high) / <alpha-value>)',
        'surface-highest': 'rgb(var(--c-surface-highest) / <alpha-value>)',
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        outline: 'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
        primary: 'rgb(var(--c-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--c-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--c-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--c-on-primary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--c-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
        secondary: 'rgb(var(--c-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--c-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--c-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--c-on-secondary-container) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
        tertiary: 'rgb(var(--c-tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--c-on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--c-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--c-inverse-primary) / <alpha-value>)',
        error: 'rgb(var(--c-error) / <alpha-value>)',
        'error-container': 'rgb(var(--c-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--c-on-error-container) / <alpha-value>)',
        gold: {
          100: 'rgb(var(--c-gold-100) / <alpha-value>)',
          500: 'rgb(var(--c-gold-500) / <alpha-value>)',
          600: 'rgb(var(--c-gold-600) / <alpha-value>)',
        },
        paper: 'rgb(var(--c-paper) / <alpha-value>)',
        ink: 'rgb(var(--c-ink) / <alpha-value>)',
        silver: 'rgb(var(--c-silver) / <alpha-value>)',
        sea: 'rgb(var(--c-sea) / <alpha-value>)',
        timber: 'rgb(var(--c-timber) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Archivo', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        script: ['"Fraunces"', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg': ['clamp(2.25rem, 5.5vw, 3.5rem)', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '0.08em' }],
        'headline-lg': ['clamp(1.75rem, 4vw, 2.5rem)', { lineHeight: '1.12', fontWeight: '700', letterSpacing: '0.05em' }],
        'headline-md': ['1.375rem', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '0.04em' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '600', letterSpacing: '0.03em' }],
        'price-display': ['1.25rem', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '0.01em' }],
        'body-lg': ['1rem', { lineHeight: '1.65', fontWeight: '400', letterSpacing: '0.01em' }],
        'body-md': ['0.875rem', { lineHeight: '1.6', fontWeight: '400', letterSpacing: '0.01em' }],
        'body-sm': ['0.75rem', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0.02em' }],
        'label-caps': ['0.6875rem', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '0.14em' }],
        'label-caps-sm': ['0.625rem', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '0.12em' }],
        'script-accent': ['clamp(1.5rem, 3.5vw, 1.9rem)', { lineHeight: '1.15', fontWeight: '400', fontStyle: 'italic', letterSpacing: '0.01em' }],
      },
      boxShadow: {
        card: '0 1px 2px rgba(17,17,17,0.04), 0 8px 24px rgba(143,114,34,0.07)',
        'card-hover': '0 2px 4px rgba(17,17,17,0.05), 0 18px 40px rgba(143,114,34,0.14)',
        float: '0 8px 24px rgba(143,114,34,0.14)',
        'float-strong': '0 12px 32px rgba(143,114,34,0.24)',
        soft: '0 1px 2px rgba(17,17,17,0.03)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.375rem',
        xl: '0.625rem',
        '2xl': '0.875rem',
        '3xl': '1.25rem',
      },
      maxWidth: {
        page: '80rem',
      },
    },
  },
  plugins: [],
};